[zh]
# title = "My blog"
weight = 1
LanguageName = "中文"
contentDir = "content/chinese"

[en]
# title = "My blog"
description = "read / code"
weight = 2
LanguageName = "EN"
contentDir = "content/english"

# [ar]
# title = "فلانة الفلانية"
# description = "أنا أعمل كمطورة ويب في شركة س"
# contentDir = "content/arabic" 
# weight = 2
# LanguageDirection = "rtl" 
# LanguageName = "AR"
