baseURL = "https://www.peterlau.xyz"
languageCode = 'en-us'
title = 'CodeMist'

theme = "hugo-theme-flat"
enableRobotsTXT = true
hasCJKLanguage = true
paginate = 6

ignorefiles = [ "_draft/.*" ]

# these values are hugo built in markup config
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = false
noHl = false
style = 'monokailight'
# style = 'monokai'
# style = 'dracula'
tabWidth = 2

[params]
mainSections = ['posts']
show_comments = true
ga = 'G-YEDG0XLC2T'

## uncomment belows and set proper values to enable remark42
# [params.remark42]
# host=''
# site_id=''
# max_shown_comments=100
# theme='light'
# locale='en'
# show_email_subscription=false
# simple_view=true

[params.utterances]
repo = 'supeterlau/supeterlau.github.io'
issue = 'pathname'
theme = 'github-light'

# you can set multi row of footers like these
[[params.footer_rows]]
[[params.footer_rows.items]]
name = "Creative Commons Attribution 4.0 International"
url = "https://creativecommons.org/licenses/by/4.0/"
pre = "Copyright <a href=\"https://creativecommons.org/licenses/by/4.0/\">CC BY-4.0</a> 2022"

[[params.footer_rows]]
[[params.footer_rows.items]]
name = "Hugo"
url = "https://gohugo.io"
pre = "Powered by <a href=\"https://gohugo.io\">Hugo</a>"
[[params.footer_rows.items]]
name = "theme flat"
# url = "https://github.com/fayemini/hugo-theme-flat.git"
# pre = "Theme <a href=\"https://github.com/fayemini/hugo-theme-flat\">hugo-theme-flat</a>"
url = "https://github.com/leafee98/hugo-theme-flat.git"
pre = "Theme <a href=\"https://github.com/leafee98/hugo-theme-flat\">hugo-theme-flat</a>"


[[menus.left]]
name = "Posts"
url = "/posts/"
weight = 30

# [[menus.main]]
# name = "Essays"
# url = "/essays/"
# weight = 40

[[menus.left]]
name = "\"I saw the best minds of my generation destroyed by madness\""
url = ""
weight = 40

[[menus.right]]
pageref = "contact"
name = "Contact"
weight = 80

# 2-level sub menus are supported
# [[menus.main]]
# name = "Services"
# weight = 60
# [[menus.main]]
# parent = "Services"
# name = "Service A"
# url = "#"
# [[menus.main]]
# parent = "Services"
# name = "Service B"
# url = "#"

defaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    description = "Blog about Hugo, web design, CSS/SCSS, SEO, Tools"
    mydomain = "peterlau.xyz"
		# contentDir = "content/posts/en"
  [languages.zh]
	  title = "码雾"
    languageName = "Chinese"
    weight = 2
    mydomain = "peterlau.xyz/zh"
		# contentDir = "content/posts/zh"
